// Mocks generated by Mockito 5.0.16 from annotations
// in gelato_gallery/test/features/gallery/domain/repository/gallery_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:gelato_gallery/features/gallery/data/models/photo_model.dart'
    as _i4;
import 'package:gelato_gallery/features/gallery/data/sources/gallery_local_data_source.dart'
    as _i5;
import 'package:gelato_gallery/features/gallery/data/sources/gallery_remote_data_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [GalleryRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGalleryRemoteDataSource extends _i1.Mock
    implements _i2.GalleryRemoteDataSource {
  MockGalleryRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.PhotoModel>> getPhotos(String? page, String? limit) =>
      (super.noSuchMethod(Invocation.method(#getPhotos, [page, limit]),
              returnValue:
                  Future<List<_i4.PhotoModel>>.value(<_i4.PhotoModel>[]))
          as _i3.Future<List<_i4.PhotoModel>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GalleryLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGalleryLocalDataSource extends _i1.Mock
    implements _i5.GalleryLocalDataSource {
  MockGalleryLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String toString() => super.toString();
}
